// <auto-generated />
using System;
using MedicalResearch.BillingData.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalResearch.BillingData.Migrations
{
    [DbContext(typeof(BillingDataDbContext))]
    partial class BillingDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.BillableVisitEntity", b =>
                {
                    b.Property<Guid>("VisitGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExecutionEndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParticipantIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudyExecutionIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UniqueExecutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitProcedureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitGuid");

                    b.HasIndex("StudyExecutionIdentifier");

                    b.ToTable("BdrBillableVisits", (string)null);
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.BillingDemandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudyExecutionIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TransmissionDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudyExecutionIdentifier");

                    b.ToTable("BdrBillingDemands", (string)null);
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrectionOfInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OffcialInvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentReceivedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentSubmittedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudyExecutionIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TransmissionDateUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorrectionOfInvoiceId");

                    b.HasIndex("StudyExecutionIdentifier");

                    b.ToTable("BdrInvoices", (string)null);
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.StudyExecutionScopeEntity", b =>
                {
                    b.Property<Guid>("StudyExecutionIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExecutingInstituteIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtendedMetaData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteRelatedCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SiteRelatedTaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudyWorkflowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudyWorkflowVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudyExecutionIdentifier");

                    b.ToTable("BdrStudyExecutionScopes", (string)null);
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.VisitBillingRecordEntity", b =>
                {
                    b.Property<long>("BillingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BillingRecordId"));

                    b.Property<Guid?>("BillingDemandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutorValidationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FixedExecutionState")
                        .HasColumnType("int");

                    b.Property<decimal>("FixedPriceOfTasks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedPriceOfVisit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FixedTaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SponsorValidationDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TasksRelatedInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VisitGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BillingRecordId");

                    b.HasIndex("BillingDemandId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("VisitGuid");

                    b.ToTable("BdrVisitBillingRecords", (string)null);
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.BillableVisitEntity", b =>
                {
                    b.HasOne("MedicalResearch.BillingData.Persistence.StudyExecutionScopeEntity", "StudyExecution")
                        .WithMany("BillableVisits")
                        .HasForeignKey("StudyExecutionIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyExecution");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.BillingDemandEntity", b =>
                {
                    b.HasOne("MedicalResearch.BillingData.Persistence.StudyExecutionScopeEntity", "StudyExecution")
                        .WithMany("BillingDemands")
                        .HasForeignKey("StudyExecutionIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyExecution");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.InvoiceEntity", b =>
                {
                    b.HasOne("MedicalResearch.BillingData.Persistence.InvoiceEntity", "CorrectionOf")
                        .WithMany("Corrections")
                        .HasForeignKey("CorrectionOfInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedicalResearch.BillingData.Persistence.StudyExecutionScopeEntity", "StudyExecution")
                        .WithMany("Invoices")
                        .HasForeignKey("StudyExecutionIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrectionOf");

                    b.Navigation("StudyExecution");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.VisitBillingRecordEntity", b =>
                {
                    b.HasOne("MedicalResearch.BillingData.Persistence.BillingDemandEntity", "AssignedDemand")
                        .WithMany("BillingRecords")
                        .HasForeignKey("BillingDemandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedicalResearch.BillingData.Persistence.InvoiceEntity", "AssignedInvoice")
                        .WithMany("BillingRecord")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedicalResearch.BillingData.Persistence.BillableVisitEntity", "BillableVisit")
                        .WithMany("BillingRecord")
                        .HasForeignKey("VisitGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedDemand");

                    b.Navigation("AssignedInvoice");

                    b.Navigation("BillableVisit");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.BillableVisitEntity", b =>
                {
                    b.Navigation("BillingRecord");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.BillingDemandEntity", b =>
                {
                    b.Navigation("BillingRecords");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.InvoiceEntity", b =>
                {
                    b.Navigation("BillingRecord");

                    b.Navigation("Corrections");
                });

            modelBuilder.Entity("MedicalResearch.BillingData.Persistence.StudyExecutionScopeEntity", b =>
                {
                    b.Navigation("BillableVisits");

                    b.Navigation("BillingDemands");

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
